### ISSUE TITLE
type of exported infected and probability maps

### ISSUE THREAD

**Issue by petrasovaa** [ncsu-landscape-dynamics/r.pops.spread#14]
Currently they are saved as DCELL, is that intention? Integers might be enough here.

**Comment by petrasovaa** [comment]
Just to clarify, I am asking because I was using v.to.rast with -v flag that works only for CELL

**Comment by wenzeslaus** [comment]
I'm looking at the source code. It is a bug I introduced when removing the GRASS functionality from pops::Raster. Please workaround it with r.mapcalc if you need that right now or locally in source code by changing DCELL_TYPE to CELL_TYPE (if you need saved are integeres), but otherwise I should be able to fix this soon.
